### ISSUE TITLE
instead of manually doin all this

### ISSUE THREAD

**Issue by rungulus** [runguszone/roosterteeth-archival-website#1]
ideally we can pull from like a json file where you got

    channel
        show name
            link to archive/link to playlist
            status (downloading/archiving/not downloaded/archived/etc)

from there we can build the page. detect no links from just seeing if there isn't a link in the json object, and show up under archived depending on the status.

we can "dynamically" update this by hosting the file on a site (rungus.zone) and run the code to build the page in browser, but that could be slow! we can also probably use github deploy actions for this too

**Comment by tgb20** [comment]
I would like to assist with this website. Is it possible we could move it to a framework like [Astro](https://astro.build)? I can do the migration. This would allow for a lot less manual steps in the build process, and we wouldn't have to write any custom deployment scripts, while still having a static site output.

**Comment by rungulus** [comment]
i say go for it, i've never messed around with Astro before but let me know if you can get it working and we can try to migrate.

**Comment by tgb20** [comment]
I did most of the work in #6, still working on bringing all the data over
