### ISSUE TITLE
Fix Masonry CSS

### ISSUE THREAD

**Issue by tgb20** [runguszone/roosterteeth-archival-website#10]
Right now each section is the same height, need to auto generate the layout the allows masonry layout

**Comment by rungulus** [comment]
could use this? would mean adding a new dependency tho
https://getbootstrap.com/docs/5.0/examples/masonry/

**Comment by tgb20** [comment]
I don't think it would hurt

**Comment by rungulus** [comment]
fixed in 60f6304
